# Exemplo : Precificação de imóveis

* **Contexto**: Imobiliária focada na venda de imóveis de terceiros. 

* **Objetivo analítico**: Como utilizar o *PyCaret* para a precificação de imóveis. Através de um conjunto de preditores busca-se estimar o preço de uma residência.

## Estratégias de negócio:

* **Precificação de Oferta**: Utilizar a estimativa do preço do imóvel para precificá-lo ao consumidor final.
* **Balizamento de Captação**: Ajustar o preço sugerido pelo proprietário ao valor estimado pelo modelo.
* **Priorização de Carteira**: Priorizar a venda de imóveis dependendo da estimativa do preço.
* **Alocação Inteligente de Equipe**: Direcionar corretores com perfis específicos (ex.: especialistas em alto padrão) de acordo com a faixa de preço estimada pelo modelo para cada imóvel.

**Imports requeridos para a execução do estudo**

In [1]:
#Bibliotecas básicas
import pandas as pd     #Manipulação dos dados
import numpy as np      #Operações multidimensionais e matemáticas
import matplotlib.pyplot as plt    #Gráficos
import matplotlib.ticker as ticker #Remover a notação científica do gráfico
##Machine learning
from pycaret.regression import * 
##Eliminar os warnings
import warnings
warnings.filterwarnings("ignore")
##Ver todas as colunas do data frame
pd.set_option('display.max_columns', None)
##Extrair os valores do feature importance
import sklearn as sk
#Definir o formato de exibição tipo float para evitar notação científica
pd.options.display.float_format = '{:.2f}'.format
#MAPE (métrica de avaliação)
from sktime.performance_metrics.forecasting import mean_absolute_percentage_error
##Extrair os valores do feature importance
import sklearn as sk

**Versões do Python e PyCaret instaladas**

In [2]:
#Identificar a versão do Python
import sys
print(f"Versão do Python: {sys.version}") #Versão do Python: 3.11.8

Versão do Python: 3.11.8 | packaged by Anaconda, Inc. | (main, Feb 26 2024, 21:34:05) [MSC v.1916 64 bit (AMD64)]

In [3]:
#Identificar a versão do PyCaret
import pycaret
print(f"Versão do PyCaret: {pycaret.__version__}") #Versão do PyCaret: 3.3.0

Versão do PyCaret: 3.3.0

# 1 - Visão geral dos dados

## Importação dos dados

* Base histórica de imóveis comercializados pela corretora.

In [4]:
#Importar a base de dados
df =  pd.read_csv('base_dados.csv', sep = ';')
#Visualizar
df.head(3)

,ID_RESIDENCIA,PRECO,AREA,QUARTOS,BANHEIROS,ANDARES,FLAG_CENTRO,FLAG_QUARTO_HOSPEDE,FLAG_PORAO,FLAG_AGUA_MORNA,FLAG_AR_CONDICIONADO,VAGAS_ESTACIONAMENTO,FLAG_AREA_PREFERENCIAL,MOBILIADA
0,A1,13300000,7420,4.00,2.00,3,SIM,NAO,NAO,NaN,SIM,2.00,SIM,SIM
1,A2,12250000,8960,4.00,4.00,4,SIM,NAO,NaN,NAO,SIM,3.00,NAO,SIM
2,A3,12250000,9960,NaN,2.00,2,SIM,NAO,SIM,NAO,NAO,2.00,SIM,PARCIALMENTE

**Nota**: *NaN* - not as a number (é um valor nulo).
* Cenários reais de negócios, bases de dados raramente são extraídas de forma perfeita. É muito comum existirem dados com valores ausentes por diversas razões. Cabe ao cientista quantificar o percentual de valores ausentes por variável e definir uma estratégia de atuação na modelagem - **tipo de imputação** (preenchimento de lacunas).
  * É importante saber diferenciar a estratégia de imputação de uma variável categórica e outra contínua.

## Análise exploratória dos dados

In [5]:
#Volumetria 
df.shape[0] #Total de observações: 545

545

In [6]:
#Características da base de dados
df.info()
#Nome da variável (Column), 
#Contagem de observações não nulas (Non-Null Count) 
#Tipo das variáveis (Dtype): object - string/texto, int64 - número inteiro, float64 - decimal

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ID_RESIDENCIA           545 non-null    object
 1   PRECO                   545 non-null    int64
 2   AREA                    545 non-null    int64
 3   QUARTOS                 481 non-null    float64
 4   BANHEIROS               465 non-null    float64
 5   ANDARES                 545 non-null    int64
 6   FLAG_CENTRO             533 non-null    object
 7   FLAG_QUARTO_HOSPEDE     523 non-null    object
 8   FLAG_PORAO              510 non-null    object
 9   FLAG_AGUA_MORNA         469 non-null    object
 10  FLAG_AR_CONDICIONADO    532 non-null    object
 11  VAGAS_ESTACIONAMENTO    485 non-null    float64
 12  FLAG_AREA_PREFERENCIAL  527 non-null    object
 13  MOBILIADA               493 non-null    object
dtypes: float64(3), int64(3), object(8)
memory usage: 59.7+ KB

In [7]:
#ID_RESIDENCIA - é o código de casa: Espera-se que cada linha apresente um único código
## É uma forma de verificação e validação dos dados.
df['ID_RESIDENCIA'].nunique() #545 - Cada linha é um único ID
                              #Se existisse valores duplicados seria preciso avaliar o que fazer com eles

545

**Observações sobre variáveis categóricas**:

* Variável Categórica **Ordinal**: Tem ordem implícita.
    * **Exemplo**: *Nível de Escolaridade* (Valores: Fundamental < Médio < Superior).
* Variável Categórica **Nominal**:  Sem ordem natural.
    * **Exemplo**: *Cor dos Olhos* (Valores: Azul, Verde, Castanho).

In [8]:
#Quais as classes da variável MOBILIADA? 
df['MOBILIADA'].drop_duplicates() #Essa variável pode ser vista como ordinal (ordem/ranqueamento).
                                  #Uma casa mobiliada pode ser vista como uma casa melhor (com o preço mais elevado) que uma parcial ou sem mobília.

0              SIM
2     PARCIALMENTE
7              NAO
12             NaN
Name: MOBILIADA, dtype: object

In [22]:
df['MOBILIADA'].value_counts(dropna=False) # 52 observações sem informação sobre a mobília

PARCIALMENTE    209
NAO             154
SIM             130
NaN              52
Name: MOBILIADA, dtype: int64

In [12]:
#Frequência relativa
df['MOBILIADA'].value_counts(normalize=True, dropna=False) * 100

PARCIALMENTE   38.35
NAO            28.26
SIM            23.85
NaN             9.54
Name: MOBILIADA, dtype: float64

In [14]:
df.groupby('MOBILIADA')['PRECO'].mean() 
#Em média, os imóveis que possuem mobília apresentam um preço de venda superior aos demais.

MOBILIADA
NAO            4073636.36
PARCIALMENTE   4949937.80
SIM            5592995.69
Name: PRECO, dtype: float64

**Pergunta**: que tipo de análise eu poderia fazer para as variáveis quantitativas?

# 2 - PyCaret

## 2.1 - Setup

* Esta função tem vários parâmetros e prepara o ambiente de modelagem, ou seja, realiza o pré-processamento dos dados (**imputação**, **normalização** e **encoding**) e os divide entre treinamento e teste.

In [15]:
exp = setup(df, target = 'PRECO', session_id = 1935, train_size = 0.65, ignore_features=['ID_RESIDENCIA'],
            normalize = True, normalize_method = 'minmax', numeric_imputation = 'median', categorical_imputation = 'mode',
            ordinal_features = {'MOBILIADA': ['NAO','PARCIALMENTE', 'SIM'],
                               'FLAG_CENTRO': ['NAO', 'SIM'],
                               'FLAG_QUARTO_HOSPEDE': ['NAO', 'SIM'],
                               'FLAG_PORAO': ['NAO', 'SIM'],
                               'FLAG_AGUA_MORNA': ['NAO', 'SIM'],
                               'FLAG_AR_CONDICIONADO': ['NAO', 'SIM'],
                               'FLAG_AREA_PREFERENCIAL': ['NAO', 'SIM']}, experiment_name= "EXP_REGRESSAO")

In [16]:
#Base de treino
df_treino = get_config('train')
#Visualização
df_treino.head(3)

,AREA,QUARTOS,BANHEIROS,ANDARES,FLAG_CENTRO,FLAG_QUARTO_HOSPEDE,FLAG_PORAO,FLAG_AGUA_MORNA,FLAG_AR_CONDICIONADO,VAGAS_ESTACIONAMENTO,FLAG_AREA_PREFERENCIAL,MOBILIADA,PRECO
229,9667,4.00,2.00,2,SIM,SIM,SIM,NAO,NAO,1.00,NAO,PARCIALMENTE,4690000
114,6800,NaN,1.00,1,SIM,SIM,SIM,NAO,NAO,NaN,NAO,SIM,6020000
405,3060,3.00,1.00,1,SIM,NAO,NAO,NAO,NAO,0.00,NaN,NAO,3465000

In [17]:
#As variáveis da base de treino transformadas após o pré-processamento
X = get_config('X_train_transformed')
X.head(3)

,AREA,QUARTOS,BANHEIROS,ANDARES,FLAG_CENTRO,FLAG_QUARTO_HOSPEDE,FLAG_PORAO,FLAG_AGUA_MORNA,FLAG_AR_CONDICIONADO,VAGAS_ESTACIONAMENTO,FLAG_AREA_PREFERENCIAL,MOBILIADA_1.0,MOBILIADA_2.0,MOBILIADA_0.0
229,0.55,0.60,0.33,0.33,1.00,1.00,1.00,0.00,0.00,0.33,0.00,1.00,0.00,0.00
114,0.35,0.40,0.00,0.00,1.00,1.00,1.00,0.00,0.00,0.00,0.00,0.00,1.00,0.00
405,0.10,0.40,0.00,0.00,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,1.00

### Comparando a variável AREA - original vs transformada

* **Original**

In [18]:
df_treino['AREA'].describe()

count     354.00
mean     5216.04
std      2245.19
min      1650.00
25%      3600.00
50%      4600.00
75%      6420.00
max     16200.00
Name: AREA, dtype: float64

* **Transformada**

In [19]:
X['AREA'].describe()

count   354.00
mean      0.25
std       0.15
min       0.00
25%       0.13
50%       0.20
75%       0.33
max       1.00
Name: AREA, dtype: float64

### Base de teste

In [20]:
#Base de teste - usada para a avaliação final dos modelos
df_teste = get_config('test')
#Visualização
df_teste.head(3)

,AREA,QUARTOS,BANHEIROS,ANDARES,FLAG_CENTRO,FLAG_QUARTO_HOSPEDE,FLAG_PORAO,FLAG_AGUA_MORNA,FLAG_AR_CONDICIONADO,VAGAS_ESTACIONAMENTO,FLAG_AREA_PREFERENCIAL,MOBILIADA,PRECO
483,6615,3.00,NaN,2,SIM,NAO,NAO,NaN,NAO,0.00,NAO,PARCIALMENTE,2940000
172,8400,NaN,1.00,2,SIM,SIM,SIM,NAO,SIM,2.00,SIM,NAO,5250000
144,4700,4.00,1.00,2,SIM,SIM,SIM,NAO,SIM,1.00,NAO,SIM,5600000

## 2.2 - Compare models

* Esta função treina e avalia o desempenho de todos os algoritmos disponíveis através da abordagem do cross-validation (o padrão são 10 folds). Ela fornece um resumo das métricas de avaliação usadas para cada modelo.
* O *compare_models* compara os modelos usando validação cruzada dentro da base de treino. A base de teste fica separada para uma avaliação final mais honesta.

In [21]:
#Quais algoritmos estão disponíveis (instalados)
models() #Todos os que possuem True estão instalados, podendo ser testados. Se for False, é possível instalar o algoritmo e utilizá-lo.

,Name,Reference,Turbo
ID,,,
lr,Linear Regression,sklearn.linear_model._base.LinearRegression,True
lasso,Lasso Regression,sklearn.linear_model._coordinate_descent.Lasso,True
ridge,Ridge Regression,sklearn.linear_model._ridge.Ridge,True
en,Elastic Net,sklearn.linear_model._coordinate_descent.Elast...,True
lar,Least Angle Regression,sklearn.linear_model._least_angle.Lars,True
llar,Lasso Least Angle Regression,sklearn.linear_model._least_angle.LassoLars,True
omp,Orthogonal Matching Pursuit,sklearn.linear_model._omp.OrthogonalMatchingPu...,True
br,Bayesian Ridge,sklearn.linear_model._bayes.BayesianRidge,True
ard,Automatic Relevance Determination,sklearn.linear_model._bayes.ARDRegression,False
par,Passive Aggressive Regressor,sklearn.linear_model._passive_aggressive.Passi...,True
ransac,Random Sample Consensus,sklearn.linear_model._ransac.RANSACRegressor,False
tr,TheilSen Regressor,sklearn.linear_model._theil_sen.TheilSenRegressor,False
huber,Huber Regressor,sklearn.linear_model._huber.HuberRegressor,True
kr,Kernel Ridge,sklearn.kernel_ridge.KernelRidge,False
svm,Support Vector Regression,sklearn.svm._classes.SVR,False
knn,K Neighbors Regressor,sklearn.neighbors._regression.KNeighborsRegressor,True
dt,Decision Tree Regressor,sklearn.tree._classes.DecisionTreeRegressor,True
rf,Random Forest Regressor,sklearn.ensemble._forest.RandomForestRegressor,True
et,Extra Trees Regressor,sklearn.ensemble._forest.ExtraTreesRegressor,True
ada,AdaBoost Regressor,sklearn.ensemble._weight_boosting.AdaBoostRegr...,True
gbr,Gradient Boosting Regressor,sklearn.ensemble._gb.GradientBoostingRegressor,True
mlp,MLP Regressor,sklearn.neural_network._multilayer_perceptron....,False
xgboost,Extreme Gradient Boosting,xgboost.sklearn.XGBRegressor,True
lightgbm,Light Gradient Boosting Machine,lightgbm.sklearn.LGBMRegressor,True
catboost,CatBoost Regressor,catboost.core.CatBoostRegressor,True
dummy,Dummy Regressor,sklearn.dummy.DummyRegressor,True

### 2.2.1 - Métrica de avaliação: MAPE (Erro Médio Percentual Absoluto)



#### Explicação 

* o MAPE indica, em média, o quão distantes estão as previsões dos valores reais, em termos percentuais. **Quanto menor o valor do MAPE, mais precisa é a previsão**. Por exemplo, um MAPE de 5% indica que, em média, as previsões estão, em média, a 5% dos valores reais (seja para mais ou menos).


$$
\text{MAPE} = \frac{1}{n} \sum_{i=1}^{n} \left( \frac{|A_i - F_i|}{A_i} \right) \times 100
$$

##### Notação

* A é o valor real;
* F é o valor previsto;
* n é o número total de observações na amostra,
* Σ representa a soma sobre todas as observações,
* | | representa o valor absoluto.

In [23]:
best_model = compare_models(sort='MAPE')

* OBS: No PyCaret, o MAPE aparece em escala decimal.

## 2.3 - Create model

* O PyCaret compara vários modelos automaticamente. Em seguida, vamos escolher a Ridge porque ela é simples, interpretável e boa para fins didáticos
* Esta função treina e avalia o desempenho de um determinado estimador utilizando a abordagem do cross-validation.

# Regressão Ridge  

A **Regressão Ridge** é uma variação da regressão linear que adiciona uma penalização **L2** (soma dos quadrados dos coeficientes) para evitar *overfitting* e melhorar a generalização do modelo.  

## Parâmetro Principal: `alpha` (λ)  

### O que faz?  
Controla a intensidade da regularização:  

- **`alpha = 0`** → Desativa a penalização (igual à regressão linear simples).  
- **`alpha > 0`** → Reduz a magnitude dos coeficientes, evitando valores extremos.  
- **Quanto maior o `alpha`**, mais os coeficientes se aproximam de zero (sem nunca zerar).

In [ ]:
#Modelo Ridge
model_ridge = create_model('ridge') 
model_ridge  # Na base de treino, aplica-se validação cruzada

In [ ]:
print(model_ridge.alpha) #alpha = 1

In [ ]:
#Avaliar o modelo na base de teste 
##Essa base foi separada no setup e não foi usada diretamente no treino do modelo
##Criar um data frame
df_teste_predicao = predict_model(model_ridge, data = df_teste)
#Visualização
df_teste_predicao.head(3)
#MAPE = 0.1876

In [ ]:
#Outra abordagem de extrair o MAPE da base de teste
mape_1 = mean_absolute_percentage_error(df_teste_predicao.PRECO, df_teste_predicao.prediction_label)
print("MAPE:", round(100 * mape_1,2)) #MAPE: 18.76

* Quando o PyCaret mostra MAPE = 0.1876, isso corresponde aproximadamente a 18,76%. Ou seja, em média, o erro absoluto da previsão equivale a cerca de 18,76% do preço real.
* Por que o MAPE não é um problema - como métrica de avaliação - neste tipo de contexto preditivo? (**Provocação**)

## 2.4 - Tune model (opcional)

* Esta função visa encontrar uma nova combinação de hiperparâmetros que possa melhorar a performance do modelo.

In [ ]:
#Simular outros valores de alfa para encontrar um resultado melhor
param = {'alpha': [0.0001, 0.01, 0.1, 1, 2, 5, 10]}

In [ ]:
tuned_model = tune_model(    model_ridge,
    optimize='MAPE',
    fold=10,
    custom_grid=param,
    search_algorithm='grid')

In [ ]:
#Avaliar o modelo tunado na base de teste
df_teste_tune = predict_model(tuned_model, data = df_teste)
#Visualização
df_teste_tune.head(3) #MAPE: 0.1876

In [ ]:
#valor do alpha = 1
print(tuned_model.alpha)

## 2.5 - Avaliação de desempenho

In [ ]:
#Panorama geral dos resultados
evaluate_model(model_ridge)

In [ ]:
#Top 10 variáveis
plot_model(model_ridge, plot = 'feature', save=True)

In [ ]:
#Ordem de importância de todas as variáveis
plot_model(model_ridge, plot = 'feature_all', save=True)

In [ ]:
#Criar um data frame do feature importance (o peso dos coeficientes estimados)
coeficientes = model_ridge.coef_
nomes_variaveis = X.columns

df_coeficientes = pd.DataFrame({
    'Feature': nomes_variaveis,
    'Coeficiente': coeficientes,
    'Importancia_absoluta': abs(coeficientes)
})

df_coeficientes = df_coeficientes.sort_values(
    by='Importancia_absoluta',
    ascending=False
)

df_coeficientes.to_csv("coeficientes_ridge.csv", sep=";", index=False)
df_coeficientes

O sinal do coeficiente indica a direção da associação com o preço previsto. O valor absoluto ajuda a enxergar quais variáveis têm maior peso no modelo. Ainda assim, isso não deve ser interpretado como causalidade.

* **O foco é preditivo e não inferencial**.

In [ ]:
#Intercepto estimado
tuned_model.intercept_ #2049016.8354677442

In [ ]:
#Salvar o erro
plot_model(model_ridge, plot = 'error', save=True)

In [ ]:
#Salvar os resíduos
plot_model(model_ridge, plot = 'residuals', save=True)

In [ ]:
#Pipeline da modelagem
plot_model(model_ridge, plot = 'pipeline', save=True)

## 2.6 - Concluir o experimento

In [ ]:
#Finalizar o modelo
## Nesta etapa, o modelo é reestimado usando toda a base disponível.
## Depois disso, ele está pronto para ser salvo e usado em novas previsões.
final_model = finalize_model(model_ridge)
final_model

Após o `finalize_model`, o objetivo não é mais avaliar o desempenho na base de teste. A avaliação já foi feita antes. Agora o objetivo é treinar a versão final do modelo para uso futuro.

In [ ]:
previsoes_df = predict_model(final_model, data=df)
#Visualização
previsoes_df.head(3)

In [ ]:
#Renomear a variável prediction_label
previsoes_df.rename(columns = {'prediction_label':'PRECO_ESTIMADO'}, inplace = True)

In [ ]:
#Visualizar
previsoes_df.head(3)

In [ ]:
#Salvar o data frame
previsoes_df.to_csv('df_estimativas.csv', header=True, index=False, sep=';')

In [ ]:
#Salvar o modelo ("CPF" do modelo)
save_model(final_model, 'ridge_model')